services:
  - type: web
    name: reddit-tracker-api
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      # Run migrations after disk is mounted in startCommand
      PYTHONPATH=/opt/render/project/src
    startCommand: |
      # Debug disk mounting
      echo "=== Checking Disk Mount ==="
      df -h
      mount | grep var
      ls -la /var/data
      echo "==========================="
      
      # Set environment variables
      export ENV=production
      export DATABASE_URL="sqlite:////var/data/reddit_analysis.db"
      export RENDER=true
      
      # Ensure database directory exists and is writable
      mkdir -p /var/data
      chmod 777 /var/data
      
      # Run migrations if needed
      PYTHONPATH=/opt/render/project/src alembic upgrade head
      
      # Debug info
      echo "=== Database Configuration ==="
      echo "Environment: $ENV"
      echo "Database Path: /var/data/reddit_analysis.db"
      echo "Render: $RENDER"
      ls -la /var/data/
      echo "==========================="
      
      # Start the application
      exec uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENV
        value: production
      - key: RENDER
        value: "true"
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PYTHON_VERSION
        value: 3.11.0
    disk:
      name: sqlite-data
      mountPath: /var/data
      sizeGB: 1