services:
  - type: web
    name: reddit-tracker-api
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      PYTHONPATH=/opt/render/project/src
    startCommand: |
      # Debug disk mounting
      echo "=== Checking Disk Mount ==="
      df -h | grep /var/data || echo "Warning: Disk not mounted!"
      ls -la /var/data || echo "Warning: Directory not accessible!"
      id  # Print current user info
      echo "==========================="
      
      # Wait for disk to be mounted
      echo "Waiting for disk mount..."
      for i in {1..30}; do
        if [ -d "/var/data" ]; then
          echo "Disk mounted successfully!"
          break
        fi
        echo "Attempt $i: Waiting for disk mount..."
        sleep 1
      done
      
      # Set environment variables
      export ENV=production
      export RENDER=true
      export DATABASE_URL="sqlite:////var/data/reddit_analysis.db"
      
      # Check directory permissions
      echo "=== Directory Permissions ==="
      ls -la /var/data/
      id
      whoami
      groups
      echo "==========================="
      
      # Run migrations if needed
      PYTHONPATH=/opt/render/project/src alembic upgrade head
      
      # Start the application
      exec uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENV
        value: production
      - key: RENDER
        value: "true"
      - key: DATABASE_URL
        value: sqlite:////var/data/reddit_analysis.db
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PYTHON_VERSION
        value: 3.11.0
    disk:
      name: sqlite-data
      mountPath: /var/data
      sizeGB: 1