services:
  - type: web
    name: reddit-tracker-api
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      PYTHONPATH=/opt/render/project/src
    startCommand: |
      # Debug disk mounting
      echo "=== Checking Disk Mount ==="
      df -h | grep /database || echo "Warning: Disk not mounted!"
      ls -la /database || echo "Warning: Directory not accessible!"
      echo "==========================="
      
      # Set environment variables
      export ENV=production
      export RENDER=true
      
      # Ensure database directory exists and has full permissions
      mkdir -p /database
      chmod -R 777 /database  # Recursive 777 to ensure all files are writable
      
      # Debug info
      echo "=== Database Configuration ==="
      echo "Environment: $ENV"
      echo "Mount Path: /database"
      echo "Database Path: /database/reddit_analysis.db"
      echo "Directory Permissions:"
      ls -la /database/
      stat -f "%A %N" /database  # Show numeric permissions
      echo "==========================="
      
      # Run migrations if needed
      PYTHONPATH=/opt/render/project/src alembic upgrade head
      
      # Start the application
      exec uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENV
        value: production
      - key: RENDER
        value: "true"
      - key: DATABASE_URL
        value: "sqlite:////database/reddit_analysis.db"
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PYTHON_VERSION
        value: 3.11.0
    disk:
      name: sqlite-data
      mountPath: /database
      sizeGB: 1