services:
  - type: web
    name: reddit-tracker-api
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      # Initialize database in project directory
      touch ./reddit_analysis_prod.db
      chmod 777 ./reddit_analysis_prod.db
      # Run migrations on the production database
      export DATABASE_URL="sqlite:///./reddit_analysis_prod.db"
      export ENV=production
      PYTHONPATH=/opt/render/project/src alembic upgrade head
    startCommand: |
      # Set database URL for production
      export DATABASE_URL="sqlite:///./reddit_analysis_prod.db"
      export ENV=production
      
      # Debug info
      echo "Database Configuration:"
      echo "DATABASE_URL=$DATABASE_URL"
      echo "ENV=$ENV"
      ls -la ./reddit_analysis_prod.db
      
      # Start the application
      exec uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: true
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        value: sqlite:///./reddit_analysis_prod.db