services:
  - type: web
    name: reddit-tracker-api
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      # Set environment variables
      export ENV=production
      export RENDER=true
      export DATABASE_URL="sqlite:////var/data/reddit_analysis.db"
      export PYTHONPATH=/opt/render/project/src
      
      # Ensure we're in the right directory
      cd /opt/render/project/src
      
      echo "=== Environment Setup ==="
      echo "Current directory: $(pwd)"
      echo "Python path: $PYTHONPATH"
      echo "Database URL: $DATABASE_URL"
      echo "==========================="
      
      echo "=== Database Status Before Migration ==="
      sqlite3 /var/data/reddit_analysis.db ".tables" || echo "No tables yet"
      echo "==========================="
      
      echo "=== Running Migrations ==="
      sqlite3 /var/data/reddit_analysis.db "DROP TABLE IF EXISTS alembic_version;"
      
      PYTHONPATH=/opt/render/project/src alembic upgrade head || {
        echo "Migration failed! Checking database state..."
        echo "Database permissions:"
        ls -la /var/data/reddit_analysis.db
        echo "Current tables:"
        sqlite3 /var/data/reddit_analysis.db ".tables"
        echo "Current schema:"
        sqlite3 /var/data/reddit_analysis.db ".schema"
        exit 1
      }
      
      echo "=== Verifying Migration ==="
      echo "Tables after migration:"
      sqlite3 /var/data/reddit_analysis.db ".tables"
      echo "Schema after migration:"
      sqlite3 /var/data/reddit_analysis.db ".schema"
      echo "==========================="
      
      # Ensure database is readable by worker
      chmod 666 /var/data/reddit_analysis.db
      
      # Start the application
      exec uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENV
        value: production
      - key: RENDER
        value: "true"
      - key: DATABASE_URL
        value: sqlite:////var/data/reddit_analysis.db
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PYTHON_VERSION
        value: 3.11.0
    disk:
      name: sqlite-data
      mountPath: /var/data
      sizeGB: 1

  - type: worker
    name: reddit-tracker-worker
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      # Wait for disk mount (up to 30 seconds)
      for i in {1..30}; do
        if [ -d "/var/data" ]; then
          echo "Disk mounted successfully"
          break
        fi
        echo "Waiting for disk mount... ($i/30)"
        sleep 1
      done

      # Verify disk mount
      if [ ! -d "/var/data" ]; then
        echo "ERROR: Disk mount failed"
        exit 1
      fi

      # Set environment variables
      export ENV=production
      export RENDER=true
      export DATABASE_URL="sqlite:////var/data/reddit_analysis.db"
      export PYTHONPATH=/opt/render/project/src
      
      cd /opt/render/project/src
      
      # Debug disk mount
      echo "=== Disk Mount Status ==="
      df -h /var/data
      ls -la /var/data/
      echo "======================="
      
      # Run in continuous loop
      while true; do
        echo "Starting telegram bot run at $(date)"
        python telegrambot.py
        echo "Sleeping for 30 minutes..."
        sleep 1800
      done
    disk:
      name: sqlite-data
      mountPath: /var/data
      sizeGB: 1