services:
  - type: web
    name: reddit-tracker-api
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      PYTHONPATH=/opt/render/project/src
    startCommand: |
      # Debug disk mounting
      echo "=== Checking Disk Mount ==="
      df -h | grep /database
      ls -la /database || echo "Directory does not exist yet"
      echo "==========================="
      
      # Set environment variables
      export ENV=production
      export DATABASE_URL="sqlite:////database/reddit_analysis.db"
      export RENDER=true
      
      # Ensure database directory exists and is writable
      mkdir -p /database
      chmod 777 /database
      
      # Run migrations if needed
      PYTHONPATH=/opt/render/project/src alembic upgrade head
      
      # Verify database setup
      echo "=== Database Configuration ==="
      echo "Environment: $ENV"
      echo "Mount Path: /database"
      echo "Database Path: /database/reddit_analysis.db"
      ls -la /database/
      echo "==========================="
      
      # Start the application
      exec uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENV
        value: production
      - key: RENDER
        value: "true"
      - key: DATABASE_URL
        value: "sqlite:////database/reddit_analysis.db"
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PYTHON_VERSION
        value: 3.11.0
    disk:
      name: sqlite-data
      mountPath: /database
      sizeGB: 1