services:
  - type: web
    name: reddit-tracker-api
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      # Ensure data directory exists and is writable
      mkdir -p /data
      chmod 777 /data
      # Initialize database in persistent storage
      export ENV=production
      export DATABASE_URL="sqlite:////data/reddit_analysis.db"
      # Run migrations
      PYTHONPATH=/opt/render/project/src alembic upgrade head
    startCommand: |
      export ENV=production
      export DATABASE_URL="sqlite:////data/reddit_analysis.db"
      
      # Debug info
      echo "=== Database Configuration ==="
      echo "Environment: $ENV"
      echo "Database Path: /data/reddit_analysis.db"
      ls -la /data/
      echo "==========================="
      
      # Start the application
      exec uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: true
      - key: PYTHON_VERSION
        value: 3.11.0
    disk:
      name: sqlite-data
      mountPath: /data
      sizeGB: 1