services:
  - type: web
    name: reddit-tracker-api
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p /data
      chmod 777 /data
      alembic upgrade head
    startCommand: gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENV
        value: production
    disk:
      name: sqlite-data
      mountPath: /data
      sizeGB: 0.5