services:
  - type: web
    name: reddit-tracker-api
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      # Set environment variables
      export ENV=production
      export RENDER=true
      export DATABASE_URL="sqlite:////var/data/reddit_analysis.db"
      export PYTHONPATH=/opt/render/project/src
      
      cd /opt/render/project/src
      
      echo "=== Environment Setup ==="
      echo "Current directory: $(pwd)"
      echo "Python path: $PYTHONPATH"
      echo "Database URL: $DATABASE_URL"
      echo "==========================="
      
      echo "=== Disk Mount Check ==="
      echo "Disk contents:"
      ls -la /var/data/
      echo "Disk permissions:"
      getfacl /var/data/
      echo "==========================="
      
      echo "=== Database Status Before Migration ==="
      sqlite3 /var/data/reddit_analysis.db ".tables" || echo "No tables yet"
      echo "==========================="
      
      echo "=== Running Migrations ==="
      sqlite3 /var/data/reddit_analysis.db "DROP TABLE IF EXISTS alembic_version;"
      
      PYTHONPATH=/opt/render/project/src alembic upgrade head || {
        echo "Migration failed! Checking database state..."
        echo "Database permissions:"
        ls -la /var/data/reddit_analysis.db
        echo "Current tables:"
        sqlite3 /var/data/reddit_analysis.db ".tables"
        echo "Current schema:"
        sqlite3 /var/data/reddit_analysis.db ".schema"
        exit 1
      }
      
      echo "=== Verifying Migration ==="
      echo "Tables after migration:"
      sqlite3 /var/data/reddit_analysis.db ".tables"
      echo "Schema after migration:"
      sqlite3 /var/data/reddit_analysis.db ".schema"
      echo "==========================="
      
      # Ensure database is readable by worker
      chmod 666 /var/data/reddit_analysis.db
      
      exec uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENV
        value: production
      - key: RENDER
        value: "true"
      - key: DATABASE_URL
        value: sqlite:////var/data/reddit_analysis.db
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PYTHON_VERSION
        value: 3.11.0
    disk:
      name: sqlite-data
      mountPath: /var/data
      sizeGB: 1

  - type: worker
    name: reddit-tracker-worker
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      export ENV=production
      export RENDER=true
      export DATABASE_URL="sqlite:////var/data/reddit_analysis.db"
      export PYTHONPATH=/opt/render/project/src
      
      cd /opt/render/project/src
      
      echo "=== Worker Environment Setup ==="
      echo "Current directory: $(pwd)"
      echo "Python path: $PYTHONPATH"
      echo "Database URL: $DATABASE_URL"
      
      echo "=== Disk Mount Check ==="
      echo "Disk contents:"
      ls -la /var/data/
      echo "Disk permissions:"
      getfacl /var/data/
      
      echo "=== Database Access Check ==="
      echo "Database exists:"
      test -f /var/data/reddit_analysis.db && echo "Yes" || echo "No"
      echo "Database permissions:"
      ls -la /var/data/reddit_analysis.db
      echo "Database readable:"
      test -r /var/data/reddit_analysis.db && echo "Yes" || echo "No"
      echo "==========================="
      
      # Add a small delay to ensure web service is fully initialized
      sleep 10
      
      while true; do
        echo "=== Starting Telegram Bot Run ==="
        date
        python telegrambot.py
        echo "=== Finished Telegram Bot Run ==="
        echo "Sleeping for 30 minutes..."
        sleep 1800
      done
    envVars:
      - key: ENV
        value: production
      - key: RENDER
        value: "true"
      - key: DATABASE_URL
        value: sqlite:////var/data/reddit_analysis.db
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
    disk:
      name: sqlite-data  # Same disk as web service
      mountPath: /var/data
      sizeGB: 1