services:
  - type: web
    name: reddit-tracker-api
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      # Set environment variables
      export ENV=production
      export RENDER=true
      export DATABASE_URL="sqlite:////var/data/reddit_analysis.db"
      export PYTHONPATH=/opt/render/project/src
      
      echo "=== Current Directory ==="
      pwd
      ls -la
      echo "==========================="
      
      echo "=== Database Status Before Migration ==="
      sqlite3 /var/data/reddit_analysis.db ".tables" || echo "No tables yet"
      echo "==========================="
      
      echo "=== Running Migrations ==="
      # Ensure we're in the correct directory
      cd /opt/render/project/src
      
      # Run migrations
      echo "Current directory: $(pwd)"
      echo "Python path: $PYTHONPATH"
      echo "Database URL: $DATABASE_URL"
      
      # Run alembic migrations
      alembic upgrade head
      
      echo "=== Verifying Migration ==="
      echo "Tables after migration:"
      sqlite3 /var/data/reddit_analysis.db ".tables"
      echo "Schema after migration:"
      sqlite3 /var/data/reddit_analysis.db ".schema"
      echo "==========================="
      
      # Start the application
      exec uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENV
        value: production
      - key: RENDER
        value: "true"
      - key: DATABASE_URL
        value: sqlite:////var/data/reddit_analysis.db
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PYTHON_VERSION
        value: 3.11.0
    disk:
      name: sqlite-data
      mountPath: /var/data
      sizeGB: 1