services:
  - type: web
    name: reddit-tracker-api
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      # Initialize database in build directory
      mkdir -p /opt/render/project/data
      touch /opt/render/project/data/reddit_analysis.db
      chmod 777 /opt/render/project/data/reddit_analysis.db
      # Run migrations
      export DATABASE_URL="sqlite:////opt/render/project/data/reddit_analysis.db"
      PYTHONPATH=/opt/render/project/src alembic upgrade head
    startCommand: |
      # Wait for disk mount (max 60 seconds)
      echo "Waiting for disk mount..."
      COUNTER=0
      while [ ! -d /data ] && [ $COUNTER -lt 60 ]; do
        echo "Attempt $COUNTER: Waiting for /data directory..."
        ls -la /
        sleep 1
        COUNTER=$((COUNTER + 1))
      done

      if [ ! -d /data ]; then
        echo "Error: /data directory not mounted after 60 seconds"
        exit 1
      fi

      echo "Data directory mounted. Setting up permissions..."
      # Set up data directory
      chmod 777 /data
      
      # Copy database if it doesn't exist
      if [ ! -f /data/reddit_analysis.db ]; then
        echo "Copying database to mounted volume..."
        cp -f /opt/render/project/data/reddit_analysis.db /data/
        chmod 777 /data/reddit_analysis.db
      fi
      
      # Debug info
      echo "Data directory contents:"
      ls -la /data
      echo "Database file details:"
      ls -la /data/reddit_analysis.db || echo "Warning: Database file not found"
      echo "Process information:"
      id
      
      # Start the application
      exec uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: true
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        value: sqlite:////data/reddit_analysis.db?mode=ro
    disk:
      name: sqlite-data
      mountPath: /data
      sizeGB: 1