services:
  - type: web
    name: reddit-tracker-api
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      PYTHONPATH=/opt/render/project/src
    startCommand: |
      # Debug disk mounting
      echo "=== Checking Disk Mount ==="
      df -h | grep /var/data || echo "Warning: Disk not mounted!"
      ls -la /var/data || echo "Warning: Directory not accessible!"
      echo "==========================="
      
      # Set environment variables
      export ENV=production
      export RENDER=true
      
      # Ensure database directory exists and has full permissions
      mkdir -p /var/data
      chmod -R 777 /var/data  # Recursive 777 to ensure all files are writable
      
      # Debug info
      echo "=== Database Configuration ==="
      echo "Environment: $ENV"
      echo "Mount Path: /var/data"
      echo "Database Path: /var/data/reddit_analysis.db"
      echo "Directory Permissions:"
      ls -la /var/data/
      stat -f "%A %N" /var/data || stat /var/data  # Show numeric permissions (works on both BSD and Linux)
      echo "==========================="
      
      # Run migrations if needed
      PYTHONPATH=/opt/render/project/src alembic upgrade head
      
      # Start the application
      exec uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENV
        value: production
      - key: RENDER
        value: "true"
      - key: DATABASE_URL
        value: "sqlite:////var/data/reddit_analysis.db"
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PYTHON_VERSION
        value: 3.11.0
    disk:
      name: sqlite-data
      mountPath: /var/data
      sizeGB: 1