services:
  - type: web
    name: reddit-tracker-api
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      PYTHONPATH=/opt/render/project/src
    startCommand: |
      # Debug disk mounting
      echo "=== Checking Disk Mount ==="
      df -h | grep /var/data || echo "Warning: Disk not mounted!"
      ls -la /var/data || echo "Warning: Directory not accessible!"
      id  # Print current user info
      echo "==========================="
      
      # Wait for disk to be mounted
      echo "Waiting for disk mount..."
      for i in {1..30}; do
        if [ -d "/var/data" ]; then
          echo "Disk mounted successfully!"
          break
        fi
        echo "Attempt $i: Waiting for disk mount..."
        sleep 1
      done
      
      # Set environment variables
      export ENV=production
      export RENDER=true
      export DATABASE_URL="sqlite:////var/data/reddit_analysis.db"
      export PYTHONPATH=/opt/render/project/src
      
      # Run database migrations
      echo "=== Running Database Migrations ==="
      echo "Environment: $ENV"
      echo "Database URL: $DATABASE_URL"
      echo "Python Path: $PYTHONPATH"
      alembic current || echo "No current migration"
      alembic upgrade head || {
        echo "Migration failed! Checking database:"
        ls -la /var/data/
        sqlite3 /var/data/reddit_analysis.db ".tables" || echo "Cannot access database"
        exit 1
      }
      echo "=== Migration Complete ==="
      
      # Verify database
      echo "=== Database Status ==="
      sqlite3 /var/data/reddit_analysis.db ".tables" || echo "Cannot access database"
      echo "==========================="
      
      # Start the application
      exec uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENV
        value: production
      - key: RENDER
        value: "true"
      - key: DATABASE_URL
        value: sqlite:////var/data/reddit_analysis.db
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PYTHON_VERSION
        value: 3.11.0
    disk:
      name: sqlite-data
      mountPath: /var/data
      sizeGB: 1